spring:
  application:
    name: agile-tracker
  data:
    mongodb:
      uri: mongodb+srv://rathourpearl:HL5eE0vN3b4aLbIJ@cluster3.ftvkd5b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster3
      database: AgileTracker
      auto-index-creation: true

server:
  port: 8080